// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Company struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Contact struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Phone       sql.NullString `json:"phone"`
	Email       sql.NullString `json:"email"`
	Address     sql.NullString `json:"address"`
	BankAccount sql.NullString `json:"bank_account"`
	ContactType string         `json:"contact_type"`
	Balance     string         `json:"balance"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Coupon struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	CouponType  string         `json:"coupon_type"`
	Amount      string         `json:"amount"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type File struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Url       string       `json:"url"`
	FileType  string       `json:"file_type"`
	CompanyID int64        `json:"company_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Payment struct {
	ID            int64          `json:"id"`
	TransactionID sql.NullInt64  `json:"transaction_id"`
	CompanyID     int64          `json:"company_id"`
	Code          string         `json:"code"`
	Date          time.Time      `json:"date"`
	Amount        string         `json:"amount"`
	Note          sql.NullString `json:"note"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Product struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Cost        sql.NullString `json:"cost"`
	Price       sql.NullString `json:"price"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ProductsCategoriesLink struct {
	CategoryID int64 `json:"category_id"`
	ProductID  int64 `json:"product_id"`
}

type Transaction struct {
	ID              int64          `json:"id"`
	Code            string         `json:"code"`
	Date            time.Time      `json:"date"`
	Subtotal        string         `json:"subtotal"`
	Discount        sql.NullString `json:"discount"`
	Note            sql.NullString `json:"note"`
	ContactID       int64          `json:"contact_id"`
	CompanyID       int64          `json:"company_id"`
	TransactionType string         `json:"transaction_type"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type TransactionItem struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	ProductID     sql.NullInt64  `json:"product_id"`
	ProductName   string         `json:"product_name"`
	Quantity      string         `json:"quantity"`
	Price         string         `json:"price"`
	Discount      sql.NullString `json:"discount"`
	Note          sql.NullString `json:"note"`
}

// up_users
type UpUser struct {
	ID                 int64          `json:"id"`
	Name               sql.NullString `json:"name"`
	Username           string         `json:"username"`
	Email              string         `json:"email"`
	Provider           string         `json:"provider"`
	Password           string         `json:"password"`
	ResetPasswordToken sql.NullString `json:"reset_password_token"`
	ConfirmationToken  string         `json:"confirmation_token"`
	Confirmed          bool           `json:"confirmed"`
	Blocked            bool           `json:"blocked"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type UpUsersCompaniesLink struct {
	UserID    int64  `json:"user_id"`
	CompanyID int64  `json:"company_id"`
	Role      string `json:"role"`
}
