// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Company struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

// up_users
type UpUser struct {
	ID                 int64          `json:"id"`
	Name               sql.NullString `json:"name"`
	Username           string         `json:"username"`
	Email              string         `json:"email"`
	Provider           string         `json:"provider"`
	Password           string         `json:"password"`
	ResetPasswordToken sql.NullString `json:"reset_password_token"`
	ConfirmationToken  string         `json:"confirmation_token"`
	Confirmed          bool           `json:"confirmed"`
	Blocked            bool           `json:"blocked"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type UpUsersCompaniesLink struct {
	UserID    int64 `json:"user_id"`
	CompanyID int64 `json:"company_id"`
}
