// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Company struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Phone     sql.NullString `json:"phone"`
	Email     sql.NullString `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Contact struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Phone       sql.NullString `json:"phone"`
	Email       sql.NullString `json:"email"`
	Address     sql.NullString `json:"address"`
	BankAccount sql.NullString `json:"bank_account"`
	ContactType string         `json:"contact_type"`
	Balance     string         `json:"balance"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Coupon struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	CouponType  string         `json:"coupon_type"`
	Amount      string         `json:"amount"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Product struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Cost        sql.NullString `json:"cost"`
	Price       sql.NullString `json:"price"`
	CompanyID   int64          `json:"company_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ProductsCategoriesLink struct {
	CategoryID int64 `json:"category_id"`
	ProductID  int64 `json:"product_id"`
}

// up_users
type UpUser struct {
	ID                 int64          `json:"id"`
	Name               sql.NullString `json:"name"`
	Username           string         `json:"username"`
	Email              string         `json:"email"`
	Provider           string         `json:"provider"`
	Password           string         `json:"password"`
	ResetPasswordToken sql.NullString `json:"reset_password_token"`
	ConfirmationToken  string         `json:"confirmation_token"`
	Confirmed          bool           `json:"confirmed"`
	Blocked            bool           `json:"blocked"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
}

type UpUsersCompaniesLink struct {
	UserID    int64  `json:"user_id"`
	CompanyID int64  `json:"company_id"`
	Role      string `json:"role"`
}
